import type { Metadata } from "next";
import "./globals.css";
import {createTheme, MantineProvider} from "@mantine/core";


// Define your custom dark theme
const darkTheme = createTheme({
    colorScheme: 'dark',
    fontFamily: 'Open Sans, sans-serif',
    colors: {
        // Define a dark color palette
        dark: [
            '#1A1A2E', // Darkest background
            '#1F1F33',
            '#24243D',
            '#2E2E4C',
            '#3A3A5A',
            '#464668',
            '#515176',
            '#63638C',
            '#7575A2',
            '#8A8AB8', // Lightest background
        ],
        // Primary color for interactive elements
        primary: [
            '#1E90FF',
            '#1C80E0',
            '#1A71C1',
            '#1861A2',
            '#165283',
            '#144264',
            '#123245',
            '#102226',
            '#0E1207',
            '#0C0208',
        ],
        // Text colors
        text: [
            '#E0E0E0', // Light text for dark background
            '#BDBDBD',
            '#9E9E9E',
            '#7F7F7F',
            '#616161',
            '#424242',
            '#3D3D3D',
            '#333333',
            '#292929',
            '#1F1F1F',
        ],
    },
    primaryColor: 'primary',
    white: '#E0E0E0', // Slightly off-white for better contrast in dark mode
    black: '#1A1A2E', // Darker black for dark mode
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
    <MantineProvider theme={darkTheme} withGlobalStyles withNormalizeCSS>
        {children}
    </MantineProvider>
    </body>
    </html>
  );
}
